import type { Metadata } from "next";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import TopBar from "@/components/shared/TopBar";
import RightBar from "@/components/shared/RightBar";
import LeftBar from "@/components/shared/LeftBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body>
          <TopBar></TopBar>
          <main className="flex flex-row w-screen h-screen">
            <LeftBar></LeftBar>
            <section className="flex-[3] bg-blue-500">{children}</section>
            <RightBar></RightBar>
            
          </main>
        </body>
      </ClerkProvider>
    </html>
  );
}
