import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import TopBar from "@/components/shared/TopBar";
import LeftSideBar from "@/components/shared/LeftSideBar";
import RightSideBar from "@/components/shared/RightSideBar";
import BottomBar from "@/components/shared/BottomBar";
import { Inter } from 'next/font/google'

const inter = Inter({
  subsets:["latin"]
})

export const metadata: Metadata = {
  title: "Nextjs Social",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body
          className={inter.className}
        >
          <TopBar></TopBar>

          <main className="bg-red-500 flex flex-row">
            <LeftSideBar></LeftSideBar>
            <section className="main-container bg-red-500 flex-[3]">
              <div className="bg-yellow-500 w-full max-w-4xl  ">{children}</div>
            </section>
            <RightSideBar></RightSideBar>
          </main>

          <BottomBar></BottomBar>
        </body>
      </ClerkProvider>
    </html>
  );
}
