import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import { Metadata } from "next";
import "../globals.css"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html>
        <body className={`${inter.className} bg-dark-1` }>{children}</body>
      </html>
    </ClerkProvider>
  );
}
