import { ClerkProvider, RedirectToSignUp } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Nextjs Social",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ClerkProvider>
        
        <body className={inter.className}>{children}</body>
      </ClerkProvider>
    </html>
  );
}
